#!/bin/bash

## export used only for bash not tcsh
    TOSROOT="/opt/tinyos-2.1.0";
    TOSDIR="$TOSROOT/tos";
    CLASSPATH=".:{$TOSROOT}/support/sdk/java";
    MAKERULES="$TOSROOT/support/make/Makerules";
    export TOSROOT;
    export TOSDIR;
    export CLASSPATH;
    export MAKERULES;
    export CC2420_CHANNEL=30;
    echo "Setting up for TinyOS 2.1.0 in a bash shell";
