/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'SensorMsg'
 * message type.
 */

public class SensorMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 4;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 10;

    /** Create a new SensorMsg of size 4. */
    public SensorMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new SensorMsg of the given data_length. */
    public SensorMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMsg with the given data_length
     * and base offset.
     */
    public SensorMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMsg using the given byte array
     * as backing store.
     */
    public SensorMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public SensorMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public SensorMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMsg embedded in the given message
     * at the given base offset.
     */
    public SensorMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new SensorMsg embedded in the given message
     * at the given base offset and length.
     */
    public SensorMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <SensorMsg> \n";
      try {
        s += "  [raw_temp=0x"+Long.toHexString(get_raw_temp())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [raw_light=0x"+Long.toHexString(get_raw_light())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_temp
    //   Field type: int, unsigned
    //   Offset (bits): 0
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_temp' is signed (false).
     */
    public static boolean isSigned_raw_temp() {
        return false;
    }

    /**
     * Return whether the field 'raw_temp' is an array (false).
     */
    public static boolean isArray_raw_temp() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_temp'
     */
    public static int offset_raw_temp() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_temp'
     */
    public static int offsetBits_raw_temp() {
        return 0;
    }

    /**
     * Return the value (as a int) of the field 'raw_temp'
     */
    public int get_raw_temp() {
        return (int)getUIntBEElement(offsetBits_raw_temp(), 16);
    }

    /**
     * Set the value of the field 'raw_temp'
     */
    public void set_raw_temp(int value) {
        setUIntBEElement(offsetBits_raw_temp(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_temp'
     */
    public static int size_raw_temp() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_temp'
     */
    public static int sizeBits_raw_temp() {
        return 16;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: raw_light
    //   Field type: int, unsigned
    //   Offset (bits): 16
    //   Size (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'raw_light' is signed (false).
     */
    public static boolean isSigned_raw_light() {
        return false;
    }

    /**
     * Return whether the field 'raw_light' is an array (false).
     */
    public static boolean isArray_raw_light() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'raw_light'
     */
    public static int offset_raw_light() {
        return (16 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'raw_light'
     */
    public static int offsetBits_raw_light() {
        return 16;
    }

    /**
     * Return the value (as a int) of the field 'raw_light'
     */
    public int get_raw_light() {
        return (int)getUIntBEElement(offsetBits_raw_light(), 16);
    }

    /**
     * Set the value of the field 'raw_light'
     */
    public void set_raw_light(int value) {
        setUIntBEElement(offsetBits_raw_light(), 16, value);
    }

    /**
     * Return the size, in bytes, of the field 'raw_light'
     */
    public static int size_raw_light() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of the field 'raw_light'
     */
    public static int sizeBits_raw_light() {
        return 16;
    }

}
